/*
 * Copyright © 2013, Adam Scarr
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package net.vektah.codeglance

import com.intellij.openapi.components.ServiceManager
import com.intellij.openapi.diagnostic.Logger
import com.intellij.openapi.editor.Editor
import com.intellij.openapi.editor.ScrollType
import com.intellij.openapi.editor.colors.ColorKey
import com.intellij.openapi.editor.event.*
import com.intellij.openapi.fileEditor.FileEditor
import com.intellij.openapi.fileEditor.TextEditor
import com.intellij.openapi.fileTypes.SyntaxHighlighterFactory
import com.intellij.openapi.project.Project
import com.intellij.psi.PsiDocumentManager
import com.intellij.ui.JBColor
import net.vektah.codeglance.config.Config
import net.vektah.codeglance.config.ConfigService
import net.vektah.codeglance.render.CoordinateHelper
import net.vektah.codeglance.render.Minimap
import net.vektah.codeglance.render.RenderTask
import net.vektah.codeglance.render.TaskRunner

import javax.swing.*
import java.awt.*
import java.awt.event.*
import java.awt.image.BufferedImage
import java.lang.ref.SoftReference

/**
 * This JPanel gets injected into editor windows and renders a image generated by GlanceFileRenderer
 */
class GlancePanel(private val project: Project, fileEditor: FileEditor, private val container: JPanel, private val runner: TaskRunner) : JPanel(), VisibleAreaListener {
    private val editor: Editor
    private var mapRef: SoftReference<Minimap>
    private val logger = Logger.getInstance(javaClass.name)
    private var updatePending: Boolean? = false
    private var dirty = false
    private val coords = CoordinateHelper()
    private val configService = ServiceManager.getService(ConfigService::class.java)
    private var config: Config? = null
    private var lastFoldCount = -1
    private var viewportColor: Color? = null
    private var lastPanel: BufferedImage? = null

    // Anonymous Listeners that should be cleaned up.
    private val componentListener: ComponentListener
    private val documentListener: DocumentListener
    private val mouseWheelListener: MouseWheelListener = MouseWheelListener()
    private val mouseListener: MouseListener = MouseListener()
    private val selectionListener: SelectionListener

    private val onConfigChange = {
        readConfig()
        updateImage()
        updateSize()
        this@GlancePanel.revalidate()
        this@GlancePanel.repaint()
    }

    init {
        this.editor = (fileEditor as TextEditor).editor

        componentListener = object : ComponentAdapter() {
            override fun componentResized(componentEvent: ComponentEvent?) {
                updateSize()
                this@GlancePanel.revalidate()
                this@GlancePanel.repaint()
            }
        }
        container.addComponentListener(componentListener)

        documentListener = object : DocumentAdapter() {
            override fun documentChanged(documentEvent: DocumentEvent?) {
                updateImage()
            }
        }
        editor.document.addDocumentListener(documentListener)

        configService.onChange(onConfigChange)

        addMouseWheelListener(mouseWheelListener)

        readConfig()

        editor.scrollingModel.addVisibleAreaListener(this)

        selectionListener = SelectionListener { repaint() }
        editor.selectionModel.addSelectionListener(selectionListener)

        addMouseListener(mouseListener)
        addMouseMotionListener(mouseListener)

        updateSize()
        mapRef = SoftReference(Minimap(configService.state!!))

        updateImage()
    }

    private fun readConfig() {
        config = configService.state

        coords.setPixelsPerLine(config!!.pixelsPerLine)
        viewportColor = Color.decode("#" + config!!.viewportColor)
    }

    /**
     * Adjusts the panels size to be a percentage of the total window
     */
    private fun updateSize() {
        if (isDisabled) {
            preferredSize = Dimension(0, 0)
        } else {
            val size = Dimension(config!!.width, 0)
            preferredSize = size
        }
    }

    private val isDisabled: Boolean
        get() = config!!.disabled || editor.document.textLength > config!!.maxFileSize || editor.document.lineCount < config!!.minLineCount

    /**
     * Fires off a new task to the worker thread. This should only be called from the ui thread.
     */
    private fun updateImage() {
        if (isDisabled) return
        if (project.isDisposed) return

        val file = PsiDocumentManager.getInstance(project).getPsiFile(editor.document) ?: return

        synchronized (this) {
            // If we have already sent a rendering job off to get processed then first we need to wait for it to finish.
            // see updateComplete for dirty handling. The is that there will be fast updates plus one final update to
            // ensure accuracy, dropping any requests in the middle.
            if (updatePending!!) {
                dirty = true
                return
            }
            updatePending = true
        }

        val hl = SyntaxHighlighterFactory.getSyntaxHighlighter(file.language, project, file.virtualFile)

        var map = mapRef!!.get()
        if (map == null) {
            map = Minimap(configService.state!!)
            mapRef = SoftReference<Minimap>(map)
        }

        runner.add(RenderTask(map, editor.document.text, editor.colorsScheme, hl, editor.foldingModel.allFoldRegions, Runnable { updateComplete() }))
    }

    private fun updateComplete() {
        synchronized (this) {
            updatePending = false
        }

        if (dirty) {
            updateImageSoon()
        }

        repaint()
    }

    private fun updateImageSoon() {
        SwingUtilities.invokeLater {
            updateImage()
            dirty = false
        }
    }

    private // Work around for apple going full retard with half pixel pixels.
            // Removed temporarily as a fix for bugged scaling on OS X
            //Float scale = (Float)Toolkit.getDefaultToolkit().getDesktopProperty("apple.awt.contentScaleFactor");
            //if (scale == null) {
            //	scale = 1.0f;
            //}
    val hidpiScale: Float
        get() {
            val scale = 1.0f

            return scale
        }

    private fun getMapYFromEditorY(y: Int): Int {
        val offset = editor.logicalPositionToOffset(editor.xyToLogicalPosition(Point(0, y)))

        return coords.offsetToScreenSpace(offset)
    }

    override fun paint(gfx: Graphics?) {
        val g = gfx as Graphics2D
        g.color = editor.colorsScheme.defaultBackground
        g.fillRect(0, 0, width, height)

        if (editor.document.textLength == 0) return

        val documentEndY = editor.logicalPositionToXY(editor.offsetToLogicalPosition(editor.document.textLength - 1)).getY()
        val visibleArea = editor.scrollingModel.visibleArea
        coords.setPanelHeight(height).setPanelWidth(width).setPercentageComplete(visibleArea.minY / (documentEndY - (visibleArea.maxY - visibleArea.minY))).setHidpiScale(hidpiScale)

        val dest = coords.imageDestination

        if (updatePending!!) {
            if (lastPanel != null) {
                g.drawImage(lastPanel,
                        dest.x, dest.y, dest.width, dest.height,
                        0, 0, lastPanel!!.width, lastPanel!!.height,
                        null)
            }
            paintVisibleWindow(g)
            return
        }

        paintSelection(g)

        val minimap = mapRef!!.get()
        if (minimap == null) {
            updateImageSoon()
            return
        }

        coords.setMinimap(minimap)

        val src = coords.imageSource

        // Draw the image and scale it to stretch vertically.
        g.drawImage(minimap.img, // source image
                dest.x, dest.y, dest.width, dest.height,
                src.x, src.y, src.width, src.height,
                null)

        if (dest.height > 0 && dest.width > 0) {

            lastPanel = BufferedImage(dest.width, dest.height, BufferedImage.TYPE_4BYTE_ABGR)
            lastPanel!!.graphics.drawImage(
                    minimap.img,
                    dest.x, dest.y, dest.width, dest.height,
                    src.x, src.y, src.width, src.height,
                    null)
        }

        paintVisibleWindow(g)
    }

    private fun paintVisibleWindow(g: Graphics2D) {
        val visibleArea = editor.scrollingModel.visibleArea
        val firstVisibleLine = getMapYFromEditorY(visibleArea.minY.toInt())
        val height = coords.linesToPixels(((visibleArea.maxY - visibleArea.minY) / editor.lineHeight).toInt())

        // Draw the current viewport
        g.color = viewportColor
        g.composite = AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.50f)
        g.drawRect(0, firstVisibleLine, width, height)
        g.composite = AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.20f)
        g.fillRect(0, firstVisibleLine, width, height)
    }

    private fun paintSelection(g: Graphics2D) {
        val selectionStartOffset = editor.selectionModel.selectionStart
        val selectionEndOffset = editor.selectionModel.selectionEnd
        val firstSelectedLine = coords.offsetToScreenSpace(selectionStartOffset)
        val firstSelectedCharacter = coords.offsetToCharacterInLine(selectionStartOffset)
        val lastSelectedLine = coords.offsetToScreenSpace(selectionEndOffset)
        val lastSelectedCharacter = coords.offsetToCharacterInLine(selectionEndOffset)

        g.composite = AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.90f)
        g.color = editor.colorsScheme.getColor(ColorKey.createColorKey("SELECTION_BACKGROUND", JBColor.BLUE))

        if (firstSelectedLine == lastSelectedLine) {
            // Single line is easy
            g.fillRect(firstSelectedCharacter, firstSelectedLine, lastSelectedCharacter - firstSelectedCharacter, config!!.pixelsPerLine)
        } else {
            // Draw the line leading in
            g.fillRect(firstSelectedCharacter, firstSelectedLine, width - firstSelectedCharacter, config!!.pixelsPerLine)

            // Then the line at the end
            g.fillRect(0, lastSelectedLine, lastSelectedCharacter, config!!.pixelsPerLine)

            if (firstSelectedLine + 1 != lastSelectedLine) {
                // And if there is anything in between, fill it in
                g.fillRect(0, firstSelectedLine + config!!.pixelsPerLine, width, lastSelectedLine - firstSelectedLine - config!!.pixelsPerLine)
            }
        }
    }

    override fun visibleAreaChanged(visibleAreaEvent: VisibleAreaEvent) {
        // TODO pending http://youtrack.jetbrains.com/issue/IDEABKL-1141 - once fixed this should be a listener
        var currentFoldCount = 0
        for (fold in editor.foldingModel.allFoldRegions) {
            if (!fold.isExpanded) {
                currentFoldCount++
            }
        }

        if (currentFoldCount != lastFoldCount) {
            updateImage()
        }

        lastFoldCount = currentFoldCount

        updateSize()
        repaint()
    }

    fun onClose() {
        container.removeComponentListener(componentListener)
        editor.document.removeDocumentListener(documentListener)
        editor.selectionModel.removeSelectionListener(selectionListener)
        removeMouseWheelListener(mouseWheelListener)
        removeMouseListener(mouseListener)
        removeMouseMotionListener(mouseListener)

        mapRef.clear()
    }

    private inner class MouseWheelListener : java.awt.event.MouseWheelListener {
        override fun mouseWheelMoved(mouseWheelEvent: MouseWheelEvent) {
            editor.scrollingModel.scrollVertically(editor.scrollingModel.verticalScrollOffset + (mouseWheelEvent.wheelRotation * editor.lineHeight * 3))
        }
    }

    private inner class MouseListener : MouseAdapter() {
        private var scrollStart: Int = 0
        private var mouseStart: Int = 0
        private val defaultCursor = Cursor(Cursor.DEFAULT_CURSOR)
        private val resizeCursor = Cursor(Cursor.W_RESIZE_CURSOR)
        private var resizing = false
        private var dragging = false
        private var resizeStart: Int = 0
        private var widthStart: Int = 0

        private fun inResizeGutter(x: Int): Boolean {
            return x >= 0 && x < 8
        }

        override fun mouseDragged(e: MouseEvent?) {


            if (resizing) {
                config!!.width = widthStart + (resizeStart - e!!.xOnScreen)
                if (config!!.width < 1) {
                    config!!.width = 1
                }
                configService.notifyChange()
            }

            if (dragging) {
                // Disable animation when dragging for better experience.
                editor.scrollingModel.disableAnimation()

                editor.scrollingModel.scrollVertically(scrollStart + coords.pixelsToLines(e!!.y - mouseStart) * editor.lineHeight)
                editor.scrollingModel.enableAnimation()
            }
        }

        override fun mousePressed(e: MouseEvent?) {
            if (!dragging && inResizeGutter(e!!.x)) {
                resizing = true
            } else if (!resizing) {
                dragging = true
            }

            if (resizing) {
                resizeStart = e!!.xOnScreen
                widthStart = config!!.width
            }

            if (dragging) {
                val visibleArea = editor.scrollingModel.visibleArea
                val firstVisibleLine = getMapYFromEditorY(visibleArea.minY.toInt())
                val height = coords.linesToPixels(((visibleArea.maxY - visibleArea.minY) / editor.lineHeight).toInt())

                val panelY = e!!.y - y

                if (config!!.jumpOnMouseDown && (panelY <= firstVisibleLine || panelY >= (firstVisibleLine + height))) {
                    editor.scrollingModel.disableAnimation()
                    editor.scrollingModel.scrollTo(editor.offsetToLogicalPosition(coords.screenSpaceToOffset(e.y, config!!.percentageBasedClick)), ScrollType.CENTER)
                    editor.scrollingModel.enableAnimation()
                }

                scrollStart = editor.scrollingModel.verticalScrollOffset
                mouseStart = e.y
            }
        }

        override fun mouseReleased(e: MouseEvent?) {
            dragging = false
            resizing = false
        }

        override fun mouseClicked(e: MouseEvent?) {
            if (!config!!.jumpOnMouseDown) {
                editor.scrollingModel.scrollTo(editor.offsetToLogicalPosition(coords.screenSpaceToOffset(e!!.y, config!!.percentageBasedClick)), ScrollType.CENTER)
            }
        }

        override fun mouseMoved(e: MouseEvent?) {
            if (inResizeGutter(e!!.x)) {
                cursor = resizeCursor
            } else {
                cursor = defaultCursor
            }
        }
    }
}
